### ISSUE TITLE
Export to elasticsearch not working

### ISSUE THREAD

**Issue by nico01f** [opensemanticsearch/open-semantic-etl#31]
Hello,

I'm setting elasticsearch to etl file, but when i ran :
`opensemanticsearch-index-web  www.emol.com`

Throw this exception on the console:
```

Traceback (most recent call last):
  File "/usr/bin/opensemanticsearch-index-web", line 258, in <module>
    connector = Connector_Web()
  File "/usr/bin/opensemanticsearch-index-web", line 18, in __init__
    Connector_File.__init__(self, verbose=verbose)
  File "/usr/lib/python3/dist-packages/opensemanticetl/etl_file.py", line 21, in __init__
    self.read_configfiles()
  File "/usr/bin/opensemanticsearch-index-web", line 75, in read_configfiles
    self.read_configfile ('/etc/opensemanticsearch/etl')
  File "/usr/lib/python3/dist-packages/opensemanticetl/etl.py", line 66, in read_configfile
    self.init_exporter()
  File "/usr/lib/python3/dist-packages/opensemanticetl/etl.py", line 51, in init_exporter
    objectreference = getattr(module, exporter)
AttributeError: module 'export_elasticsearch' has no attribute 'export_elasticsearch'
```
My etl config file:
```

#
# Solr URI and port
#

#config['export'] = 'export_solr'

# Solr server
#config['solr'] = 'http://localhost:8983/solr/'

# Solr core
#config['index'] = 'core1'


#
# Elastic Search
#

config['export'] = 'export_elasticsearch'

# Index
#config['index'] = 'opensemanticsearch'
```

How to configure opensemanticsearch to work with elasticsearch.?

Thank you!
Best regards

**Comment by Mandalka** [comment]
Thanks for bug report.

The fixed class name / code is online, new packages including this fix will be available tomorrow.

**Comment by nico01f** [comment]
Great!

Thank you!

**Comment by nico01f** [comment]
Hi, it's me again.

I'm apply the commit in my enviroment, now throw this exception:



```
opensemanticsearch-index-web  www.emol.com
Failed to parse HTTP header last-modified
Failed to parse HTTP header date
Exception while data enrichment of http://www.emol.com with plugin enhance_extract_text_tika_server: Expecting value: line 1 column 1 (char 0)
Exception while data enrichment of http://www.emol.com with plugin enhance_detect_language_tika_server: 'content'
Exception while data enrichment of http://www.emol.com with plugin enhance_contenttype_group: 'content_type'
Exception while data enrichment of http://www.emol.com with plugin enhance_extract_hashtags: 'content'
Exception while data enrichment of http://www.emol.com with plugin enhance_rdf: 'content_type'
Exception while data enrichment of http://www.emol.com with plugin enhance_pdf_ocr: 'content_type'
Error while exporting to index or database: http://www.emol.com
Traceback (most recent call last):
  File "/usr/bin/opensemanticsearch-index-web", line 281, in <module>
    connector.index(uri)
  File "/usr/bin/opensemanticsearch-index-web", line 228, in index
    parameters, data = self.process(parameters=parameters, data=data)
  File "/usr/lib/python3/dist-packages/opensemanticetl/etl.py", line 271, in process
    raise e
  File "/usr/lib/python3/dist-packages/opensemanticetl/etl.py", line 263, in process
    parameters, data = exporter.process(parameters=parameters, data=data)
  File "/usr/lib/python3/dist-packages/opensemanticetl/export_elasticsearch.py", line 38, in process
    self.update(data=data)
  File "/usr/lib/python3/dist-packages/opensemanticetl/export_elasticsearch.py", line 50, in update
    docid = data['id']
KeyError: 'id'
```

Best regards!

**Comment by Mandalka** [comment]
I think this issue for some connectors not including ID in data is fixed now. I'll test (and repair) before next package release.
